language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - mkdir -p ~/.composer
  - echo '{"config":{"github-oauth":{"github.com":"6f880c1b17f63793e72497f9658853a33ba81136"}}}' > ~/.composer/config.json
  - composer install --dev --no-interaction

script: phpunit --configuration tests/phpunit.xml --coverage-clover ./build/logs/clover.xml