language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - echo '{\"config\":{\"github-oauth\":{\"github.com\":\"6f880c1b17f63793e72497f9658853a33ba81136\"}}}' > ~/.composer/config.json
  - composer install --dev --no-interactive

script: phpunit --configuration tests/phpunit.xml